# Generated by Django 5.1.4 on 2025-01-03 17:57
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_post_tags"),
    ]

    operations = [
        TrigramExtension()
    ]
